# Generated by Django 5.1.5 on 2025-11-27 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('cloud', 'Cloud'), ('unix', 'Unix'), ('network', 'Network'), ('database', 'Database'), ('application', 'Application')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.CharField(blank=True, max_length=100)),
                ('ticket_creation_status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('servicenow_ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('servicenow_sys_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
