# Generated by Django 5.1.5 on 2025-12-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='servicenow_ticket_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
