# Generated by Django 5.1.5 on 2025-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_servicenow_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='servicenow_ticket_status',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
    ]
