# Generated by Django 5.1.5 on 2025-12-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_servicenow_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Unique email message id / UID from IMAP', max_length=255, unique=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('raw_email', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reply_sent', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(blank=True, help_text='Related Ticket created from this email', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_record', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['uid'], name='tickets_ema_uid_6e22b4_idx')],
            },
        ),
    ]
