# Generated by Django 5.1.5 on 2025-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_emailticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email')], default='web', max_length=20),
        ),
    ]
