# Generated by Django 5.1.5 on 2025-12-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_userprofile_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='must_change_password',
        ),
    ]
